// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeedPlusPlus.Data;

#nullable disable

namespace SeedPlusPlus.Data.Migrations
{
    [DbContext(typeof(SeedPlusPlusTestContext))]
    [Migration("20240401090040_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("SeedPlusPlus.Core.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VarietyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VarietyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SeedPlusPlus.Core.Products.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Left")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Right")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Left = 1,
                            Name = "Root",
                            Right = 18
                        },
                        new
                        {
                            Id = 2,
                            Left = 2,
                            Name = "Flowers",
                            ParentId = 1,
                            Right = 7
                        },
                        new
                        {
                            Id = 4,
                            Left = 3,
                            Name = "Annual flowers",
                            ParentId = 2,
                            Right = 4
                        },
                        new
                        {
                            Id = 5,
                            Left = 5,
                            Name = "Perennial flowers",
                            ParentId = 2,
                            Right = 6
                        },
                        new
                        {
                            Id = 3,
                            Left = 8,
                            Name = "Vegetables",
                            ParentId = 1,
                            Right = 17
                        },
                        new
                        {
                            Id = 6,
                            Left = 9,
                            Name = "Brassicas",
                            ParentId = 3,
                            Right = 10
                        },
                        new
                        {
                            Id = 7,
                            Left = 11,
                            Name = "Legumes",
                            ParentId = 3,
                            Right = 12
                        },
                        new
                        {
                            Id = 8,
                            Left = 13,
                            Name = "Leaf vegetables",
                            ParentId = 3,
                            Right = 14
                        },
                        new
                        {
                            Id = 9,
                            Left = 15,
                            Name = "Fruit vegetables",
                            ParentId = 3,
                            Right = 16
                        });
                });

            modelBuilder.Entity("SeedPlusPlus.Core.Products.Seeds.Variety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlantHeightInCm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Variety");
                });

            modelBuilder.Entity("SeedPlusPlus.Core.Products.Product", b =>
                {
                    b.HasOne("SeedPlusPlus.Core.Products.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeedPlusPlus.Core.Products.Seeds.Variety", "Variety")
                        .WithMany()
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("SeedPlusPlus.Core.Products.ProductCategory", b =>
                {
                    b.HasOne("SeedPlusPlus.Core.Products.ProductCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SeedPlusPlus.Core.Products.ProductCategory", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
